name: audiobookshelf_api
description: A Dart wrapper for the audiobookshelf API.
version: 0.1.0
repository: https://github.com/audiobookshelf-flutter/audiobookshelf_api

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  http_parser: ^4.0.2
  json_annotation: ^4.8.0
  mime: ^1.0.3
  socket_io_client: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  mocktail: ^0.3.0
  source_gen: ^1.2.6
  test: ^1.16.0
